sudo: false

language: rust

rust:
    - nightly
    - stable

matrix:
  allow_failures:
    - rust: nightly

after_success: 
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_RUST_VERSION = nightly ] &&
        cargo doc &&
        cp -R doc/* target/doc &&
        git clone https://github.com/davisp/ghp-import &&
        ./ghp-import/ghp-import target/doc &&
        git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --no-verify --token ${CRATESIO_TOKEN}
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ "$COVERAGE" -eq 1 ] &&
        wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&
        unzip master.zip && mv kcov-master kcov && mkdir kcov/build && cd kcov/build &&
        cmake .. && make && make install DESTDIR=../built && cd ../.. &&
        for file in ./target/debug/*; do ./kcov/built/usr/local/bin/kcov --exclude-pattern=/.cargo ./target/kcov ${file}; done &&
        ./kcov/built/usr/local/bin/kcov --coveralls-id=${TRAVIS_JOB_ID} --merge ./target/kcov-merge ./target/kcov
