[package]
name = "rouille"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
backtrace = "0.1.5"
num_cpus = "0.2.6"
rustc-serialize = "0.3"
tiny_http = "0.4.0"
term = "0.2"
threadpool = "0.1.4"
time = "0.1.31"
url = "0.2"

[dev-dependencies]
mustache = "0.6"
