[package]
name = "rouille"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
tiny_http = "0.4"
rand = "0.3.11"
rustc-serialize = "0.3"
term = "0.2"
time = "0.1.31"
url = "0.2"

[dev-dependencies]
mustache = "0.6"
