[package]
name = "rouille"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
tiny_http = "0.4.0"
term = "0.2"
time = "0.1.31"

[dev-dependencies]
mustache = "0.6"
